### ISSUE TITLE
useMemo on group tabs, sometimes hiddes the tabs for the admin

### ISSUE THREAD

**Issue by rafinskipg** [etereo-io/edge-next#39]
@ihorkitrum  i see that after creating a group, that has no content. I don't see the tabs sometimes ( try reloading the page) i think some memo properties are not allowing the user to see the group tabs

**Comment by ihorkitrum** [comment]
fixed by the [commit](https://github.com/etereo-io/edge-next/commit/b9de3e51fcf1b676ebf67e2454ff23a35c9adb3a)
