### ISSUE TITLE
RFC: Wysiwig Field Type

### ISSUE THREAD

**Issue by rafinskipg** [etereo-io/edge-next#4]
We want to add a new field type, "wysiwig" that will basically extend the actual "markdown" field, adding a wysiwig editor on top.

```javascript
{
  type: 'wysiwig',
  label: 'Description',
  options: //....
}
```

Libraries we are considering: 
- https://quilljs.com/
- Draftjs

Note: It has to be a React compatible library, that has good performance, good UI and is well mantained

**Comment by ihorkitrum** [comment]
should be closed due to https://github.com/etereo-io/edge-next/pull/20

**Comment by rafinskipg** [comment]
thanks @ihorkitrum
